language: android
jdk: oraclejdk8
sudo: false
android:
    components:
        - tools
        - build-tools-27.0.0
        - android-27
        - extra-android-m2repository
        - platform-tools
script:
    - cd opacclient
    - ./gradlew checkDebug lintDebug test jacocoRootReport coveralls
    - cat opacapp/build/reports/lint-results-debug.xml
cache:
    directories:
        - $HOME/.gradle
